require "json"


html_tmlanguage = JSON.parse(IO.read(File.join(__dir__, "html.modified.tmLanguage.json")))
js_tmlanguage = JSON.parse(IO.read(File.join(ENV["FORNIX_FOLDER"], "autogenerated", "js.tmLanguage.json")))

# put the JS inside the HTML
html_tmlanguage["repository"]["javascript"] = {
    "patterns" => js_tmlanguage["patterns"],
    "repository" => js_tmlanguage["repository"],
}

# save it to output
IO.write(
    File.join(ENV["FORNIX_FOLDER"], "autogenerated", "html.tmLanguage.json"),
    JSON.pretty_generate(html_tmlanguage)
)